# Generated by Django 4.0 on 2022-11-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctor_experience_doctor_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
