# Generated by Django 4.0.3 on 2022-10-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_developer_email_alter_developer_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='username',
        ),
    ]
